name: companydanzante
favicon: null
layout_spectrum: 0.89784
typography_spectrum: 0.56692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2d'
    - '#e3e3e3'
    - '#77b9df'
    - '#677132'
    - '#a1ab22'
  brandStrength: 0.5136865742970258
  lightness: 0.6097045929636806
  saturation: 0.9500046139582992
  rhythmicContrast: 0.6127142107579857
purpose: []
