name: companydanzante
favicon: null
layout_spectrum: 0.14932792959734797
typography_spectrum: 0.38455572770908475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5136865742970258
  lightness: 0.6097045929636806
  saturation: 0.9500046139582992
  rhythmicContrast: 0.6127142107579857
purpose: []
